name: api_service
version: 1.0.0+1
description: 'Api service provides you convenience while exchanging all requests.'
homepage: https://
repository: https://
publish_to: "none"



environment:

  sdk: ">=2.18.1 <3.0.0"

dependencies:
  logger: ^1.1.0
  shared_preferences: ^2.0.17
  http: ^0.13.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
